### ISSUE TITLE
Exercices Algo

### ISSUE THREAD

**Issue by mdevoldere** [Coleric-FOAD/Exos#1]
Déposer les exercices Algo

**Comment by mdevoldere** [comment]
Les algos du fichier .ini sont corrects. Pensez à déclarer les variables avant de les utiliser ;)

**Comment by Coleric-FOAD** [comment]
Ok Mickaël,

Je les déclare avant de commencer :

  *   Nom
  *   Type (réel, entier ...)

C'est ça ?

Cordialement,

Eric COLLE

________________________________
De : MDevoldere <notifications@github.com>
Envoyé : jeudi 24 septembre 2020 20:42
À : Coleric-FOAD/Exos <Exos@noreply.github.com>
Cc : Eric COLLE <ecolle@arfp.asso.fr>; Assign <assign@noreply.github.com>
Objet : Re: [Coleric-FOAD/Exos] Exercices Algo (#1)


Les algos du fichier .ini sont corrects. Pensez à déclarer les variables avant de les utiliser ;)

**Comment by mdevoldere** [comment]
VARIABLES
ma_variable est un entier
ou
entier ma_variable

DEBUT PROGRAMME
// algo
FIN PROGRAMME
